artifacts_root: artifacts ## name of the folder

data_ingestion:
  root_dir: artifacts/data_ingestion ## folder created after data ingestion is executed
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip ## DATA LINK
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt ## update whether the data validation is true or false

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
